name: Submit published release to WinGet community repository

on:
  release:
    types: [published]

jobs:
  publish-winget:
    name: Submit to WinGet repository
    # wingetcreate only runs on Windows
    runs-on: windows-latest
    # Only submit stable releases
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Submit package using wingetcreate
        run: |
          # Get installer info from release event
          $assets = '${{ toJSON(github.event.release.assets) }}' | ConvertFrom-Json
          $packageVersion = (${{ toJSON(github.event.release.tag_name) }}).Trim('v')
          $installerUrl = $assets | Where-Object -Property name -eq "HttpToolkit-installer-$packageVersion.exe" | Select-Object -ExpandProperty browser_download_url

          # Update package using wingetcreate
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update HTTPToolKit.HTTPToolKit `
            --version $packageVersion `
            --urls "$installerUrl|x64" `
            --submit `
            --token "${{ secrets.WINGET_GITHUB_TOKEN }}"
